#!/bin/sh

set -e
export PATH='/usr/bin:/bin:/usr/sbin:/sbin'

echo() {
  printf '%s\n' "$*"
}

help() {
  echo 'Usage:'
  echo "  $(printf %q "$(basename -- "$0")") Installer.pkg OutputDirectory"
}

PKG="$1"
OUTDIR="$2"

if [ -z "${PKG}" ] || [ -z "${OUTDIR}" ]; then
  help
  exit 1
fi

clean_up() {
  if [ -d "${UNPKG}" ]; then
    rm -Rf "${UNPKG}"
  fi
}
trap clean_up EXIT

UNPKG="$(mktemp -d "$(dirname -- "${OUTDIR}")/$(basename -- "${PKG}")-unpacked-XXXXXX")"
pkgutil --expand "${PKG}" "${UNPKG}/data"
while IFS= read -r data; do
  pushd "$(dirname -- "${data}")" > /dev/null || continue
  gzip --quiet --test Payload && {
    gzcat Payload | cpio -idmu --quiet
    rm -f Payload Bom
  }
  popd > /dev/null
done <<EOT
$(find "${UNPKG}" -name Payload -type f)
EOT
ditto "${UNPKG}/data" "${OUTDIR}"
