# https://github.com/actions/cache
# https://github.com/actions/checkout
# https://github.com/ncipollo/release-action
# https://docs.github.com/actions/using-workflows
# https://docs.github.com/actions/learn-github-actions/contexts

name: GitHub Continuous Integration

on: [push, pull_request]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:

  macos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Compile & Test
        run: make test

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Compile & Test
        run: make test
